version: 2

registries:
  private-demo:
    type: cargo-registry
    registry: "private-demo"
    url: https://dependabot-authenticated-registry-demo.swedencentral.cloudapp.azure.com/index/
    token: ${{secrets.PRIVATE_CARGO_REGISTRY_TOKEN}}

updates:
  - package-ecosystem: cargo
    directory: "/apps/hello-world-app"
    schedule:
      interval: weekly
    registries:
      - private-demo
    allow:
      - dependency-type: direct
